### ISSUE TITLE
Issue with semantic-release

### ISSUE THREAD

**Issue by meeber** [chaijs/deep-eql#44]
Commits aren't triggering new releases. This is from the latest commit:

> > deep-eql@ semantic-release /home/travis/build/chaijs/deep-eql
> > semantic-release pre && npm publish && semantic-release post
> 
> semantic-release WARN invalid config loglevel="notice"
> semantic-release ERR! pre Failed to determine new version.
> semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.

Any ideas?

**Comment by meeber** [comment]
I see there was a tagging issue mentioned in #32. It looks like the latest version on npm is 2.0.2 but the latest tag/release on github is 2.0.1. I assume that would cause the issues with semantic-release?

**Comment by keithamus** [comment]
It's likely that it is not releasing a new version because `docs`/`chore` (and other) tagged commits do not trigger a release; only `fix` and `feat` will trigger a release.
