### ISSUE TITLE
Build failing due to change in error comparison algo 

### ISSUE THREAD

**Issue by meeber** [chaijs/deep-eql#58]
Looks like #57 broke the build for IE 9 & 11 as well as Safari 10.

Apparently IE 9 & 11 add an enumerable `description` property to `Error` objects but not to `TypeError` objects, causing one of the comparison tests to fail. The `description` property appears to have the same value as `message`. (If `message` and `description` is empty, then IE 9 & 11 also add an enumerable `number` property, but that doesn't come into play with any of the tests.)

Apparently Safari 10 adds enumerable `line`, `column`, and `sourceURL` properties to all `Error` objects. This causes all of the tests to fail that expected two `Error` objects to be equal, since the `line` and/or `column` properties will always be different between `Error` objects.

What a pain. I'm not sure what the right solution is here.

**Comment by keithamus** [comment]
I think providing a custom comparator for `Error` objects that _just_ checks `name`, `message` and perahps while we're at it some node-specific ones like `code`?

We can just add another `case` statement to http://github.com/chaijs/deep-eql/blob/62e2d5142921ec2b053b3c681487d99f227df02f/index.js#L197-L238

```js
case 'Error':
  return keysEqual(leftHandOperand, rightHandOperand, ['name', 'message', 'code'], options)
```

**Comment by meeber** [comment]
Fair suggestion, and that's more or less what [lodash](https://github.com/lodash/lodash/blob/67389a8c78975d97505fa15aa79bec6397749807/lodash.js#L5735-L5736) and [Node](https://github.com/nodejs/node/blob/932a74ae747b9260ce95f401b8d58f9f791a357b/lib/internal/util/comparisons.js#L220-L223) are doing, but without checking `code`. Will sleep on it.
