### ISSUE TITLE
New version not automatically released

### ISSUE THREAD

**Issue by meeber** [chaijs/deep-eql#60]
@keithamus Similar to the issue with Chai core recently, merging the latest PR failed to auto-release a new version (v4.0).

**Comment by astorije** [comment]
I left a comment at https://github.com/chaijs/chai/pull/1200#issuecomment-424830124 on the subject but likely not in a visible enough location, sorry!
Re-posting here:

> @meeber, @keithamus, npmjs has recently invalidated all tokens, so a new one needs to be set up in the `.travis.yml` config file. I hit the same issue very recently at https://github.com/thelounge/thelounge/pull/2716.

**Comment by meeber** [comment]
Pinging @keithamus :D

**Comment by meeber** [comment]
Thanks @keithamus!
