### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by brutalcrozt** [chaijs/deep-eql#8]
Hello there, since [component not maintained as 639](https://github.com/componentjs/component/issues/639). Did you want update readme.md?

**Comment by keithamus** [comment]
Hey @brutalcrozt thanks for the issue!

I'm currently working on this and have some code on my laptop which removes this and adds a bunch of features & tests & whatnot. I'll be PRing it in the next few weeks, so not to worry :smile:

**Comment by brutalcrozt** [comment]
Glad hear that, is that includes PR for [number 4](https://github.com/chaijs/deep-eql/issues/4)?

**Comment by keithamus** [comment]
Absolutely will do :smile:
