### ISSUE TITLE
deep equal comparison fails when objects contain function

### ISSUE THREAD

**Issue by Goszu** [chaijs/deep-eql#9]
I'm trying to write unit tests for my redux-saga functionality. I found out that there is an issue when trying to compare 2 identical objects containing a function. Basically it never equals:
```
const obj1 = {
  test: function () {},
  prop: 'prop',
};
const obj2 = {
  test: function () {},
  prop: 'prop',
};
```
I've seen example created using Tape framework where that comparison worked.

**Comment by tunnckoCore** [comment]
Maybe https://github.com/tunnckoCore/function-equal can help :)

**Comment by hildjj** [comment]
This should be pretty easy on top of #12, if someone who understands componentjs enough to get the new dependency to work were to look at it.

**Comment by keithamus** [comment]
Hey @Goszu thanks for the issue. We've released a new version of deep-eql, which _does not fix this issue directly_, but it allows overriding of comparators which should enable you to achieve the behaviours you're after. Thanks for filing this!
