### ISSUE TITLE
comparing a fake Map, Set, etc throws

### ISSUE THREAD

**Issue by ljharb** [chaijs/deep-eql#99]
It seems like comparing anything that's a builtin that should have internal slots, that is only pretending to be that builtin, throws instead of returning false.

```js
var maplikeSet = new Set();
Object.defineProperty(maplikeSet, 'constructor', { enumerable: false, value: Map });

deepEqual(maplikeSet, new Map());
```

this should return false, but instead, it throws:
```js
TypeError: Method get Map.prototype.size called on incompatible receiver #<Map>
```

This bug is affecting v7 as well, so once fixed in v8, a backport would be appreciated.

I'd be happy to make a PR for both, if desired.

**Comment by keithamus** [comment]
Thanks for discovering and filing this issue. A PR would be great to see, thanks!

**Comment by ljharb** [comment]
→ #100

**Comment by ljharb** [comment]
Thanks! I’d love to make a PR to v4, but i think there’d need to be a v4 branch created first. Are you willing to make a branch and publish a backport if I make the PR?

**Comment by keithamus** [comment]
Sure. `v4` branch has been created and is ready for a PR

**Comment by ljharb** [comment]
Thanks! → #101
